# Generated by Django 4.2.10 on 2024-03-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='code',
        ),
        migrations.AddField(
            model_name='games',
            name='ball_position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='ball_position_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='ball_velocity_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='ball_velocity_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='paddleleft_position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='paddleleft_position_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='paddleright_position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='paddleright_position_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='games',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='database.users'),
        ),
        migrations.AddField(
            model_name='games',
            name='scoreleft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='scoreright',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='database.users'),
        ),
    ]
